name: autoverse
description: "Car catalog"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  logger: ^2.3.0
  shared_preferences: ^2.2.3
  google_mobile_ads: ^5.1.0
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.1.0
  lottie: ^3.1.2
  pin_code_fields: ^8.0.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  firebase_analytics: ^11.1.0
  firebase_core: ^3.1.1
  firebase_remote_config: ^5.0.2
  url_launcher: ^6.3.0
  scrollable_positioned_list: ^0.3.8
  collection: ^1.18.0
  badges: ^3.1.2
  firebase_storage: ^12.2.0
  firebase_app_check: ^0.3.1+1
  flutter_native_splash: ^2.4.1
  supabase_flutter: ^2.6.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  pixel_perfect: ^1.1.3
  flutter_localizations:
    sdk: flutter

 

flutter_native_splash:
  image: "assets/icons/splash_screen.png"
  color: "#0034f7"
  color_dark: "#0034f7"

  android_12:
    image: "assets/icons/splash_screen.png"
    icon_background_color:   "#0034f7"  
    icon_background_color_dark:   "#0034f7"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter_launcher_icons:
  android: true
  image_path_android: "assets/icons/icon.png"
  adaptive_icon_background: "assets/icons/icon.png"
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/welcome.png
    - assets/images/man.png
    - assets/images/car.png
    - assets/images/car.svg
    - assets/images/long_arrow.svg
    - assets/images/short_arrow.svg
    - assets/icons/man_icon.png
    - assets/icons/account_icon.svg
    - assets/icons/lock_icon.png
    - assets/icons/email_icon.svg
    - assets/icons/lock_icon.svg
    - assets/icons/error_cross.svg
    - assets/icons/line_eye.svg
    - assets/icons/recent.svg
    - assets/icons/filters_icon.svg
    - assets/icons/cross.svg
    - assets/icons/white_cross.svg
    - assets/icons/lens_icon.svg
    - assets/icons/home_icon.svg
    - assets/icons/list_icon.svg
    - assets/icons/compr_icon.svg
    - assets/icons/back_icon.svg
    - assets/icons/favorite.svg
    - assets/icons/active_favorite.svg
    - assets/icons/account_circle_icon.svg
    - assets/animations/correct_animation.json
    - assets/animations/denied_animation.json
    - assets/images/tik_tok.svg
    - assets/images/youtube.svg
    - assets/images/google.svg
    - assets/images/pinterest.svg
    - assets/images/sedan.svg
    - assets/images/logo.png
    - assets/configurations/cabrio.svg
    - assets/configurations/coupe.svg
    - assets/configurations/fastback.svg
    - assets/configurations/jeep.svg
    - assets/configurations/limousine.svg
    - assets/configurations/minivan.svg
    - assets/configurations/pickup.svg
    - assets/configurations/sedan.svg
    - assets/configurations/van.svg
    - assets/configurations/wagon.svg
    - assets/svg/account_active.svg
    - assets/svg/account.svg
    - assets/svg/add_active.svg
    - assets/svg/arrow_back.svg
    - assets/svg/arrow_down.svg
    - assets/svg/arrow_right.svg
    - assets/svg/arrow_up.svg
    - assets/svg/back.svg
    - assets/svg/bottom_sheet_indicator.svg
    - assets/svg/check_big.svg
    - assets/svg/check.svg
    - assets/svg/checkbox.svg
    - assets/svg/checkbox_active.svg
    - assets/svg/close_active.svg
    - assets/svg/close_comp.svg
    - assets/svg/close.svg
    - assets/svg/comp_active.svg
    - assets/svg/comp_bottom.svg
    - assets/svg/comp.svg
    - assets/svg/favorite_active.svg
    - assets/svg/favorite_bottom.svg
    - assets/svg/favorite_blue.svg
    - assets/svg/favorite.svg
    - assets/svg/filters.svg
    - assets/svg/google.svg
    - assets/svg/home_active.svg
    - assets/svg/home.svg
    - assets/svg/pinterest.svg
    - assets/svg/recent_active.svg
    - assets/svg/tik_tok.svg
    - assets/svg/Vector.svg
    - assets/svg/youtube.svg
    - assets/svg/zoom.svg
    - assets/svg/logo.svg
    - assets/car.png
    - assets/specs.png
    - assets/langs/en.json
    - assets/langs/ru.json

